[package]
name = "mattress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = "0.11.1"
aes = "0.8.1"
spake2 = "0.3.1"
nom = "7.1.1"
bitfield = "0.14.0"
